version: '3'
services:
  nasm-gcc:
    build: .
    working_dir: /usr/src
    volumes:
      - ./src:/usr/src
      - ./startup.sh:/usr/src/startup.sh
    command: ["sh", "-c", "/usr/src/startup.sh && exec bash"]
